### ISSUE TITLE
Usage Pattern for persistent loginWithPassword

### ISSUE THREAD

**Issue by ayalpani** [inProgress-team/react-native-meteor#252]
Hi!

I am having trouble implementing a simple persistent login functionality. What I basically want is:

- subscribe to a collection published on the meteor server
- show a login page when user has not logged in before
- if user is already logged in (because of persistent token), process a local collection that was part of my subscription

What I am doing is this:

```
Meteor.connect(settings.METEOR_URL)
const itemsSubId = Meteor.ddp.sub('mySubscription')

let firstTime = true
Meteor.ddp.on('ready', msg => {
  
  if (!Meteor.userId())
    return

  if (!firstTime)
    return

  if (!msg.subs.includes(itemsSubId))
    return

  firstTime = false

  // now do something with the local collection
})
```

Unfortunately, `Meteor.userId()` is always `null` but needed, so I will never get to the point of actually processing the collection.

Second, I don't understand why the on-ready callback is called twice. Once with an empty subscription, once when the collection is fully filled

Thanks for all hints!

**Comment by Nauzer** [comment]
Saw you closed the issue. It would be nice to share with the community what you've done here. 

My suggestion would be to use Meteor.user() / userId() in your container creation (see exampe in the readme) or - maybe even better for this case - use the Accounts.onLogin callback rather than DDP connected. Login takes place automatically upon connection if a valid token is still possessed by the client.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
