### ISSUE TITLE
Meteor.user() - Trackr

### ISSUE THREAD

**Issue by patrickml** [inProgress-team/react-native-meteor#55]
Is `Meteor.user()` using trackr? im trying to use react-komposer to update changes, however, whenever i update my data remotely im not seeing any changes in my app.

```
const ListOfItems = ({ items, openProject }) => (
  <List>
    {
      items.map((item, key) => (
        <ListItem key={ key }>
          <Text onPress={ openProject(item) }>
            { item.text }
          </Text>
        </ListItem>
      ))
    }
  </List>
);

const onPropsChange = (props, onData) => {
  Trackr.autorun(() => {
    const user = Meteor.user();
    console.log(user);
    onData(null, {
      ...props,
      items: [
        {
          text: user && user.profile.fullName
        }
      ]
    });
  });
};

const ProjectList = compose(onPropsChange, <Text />, <Text />)(ListOfItems);
```

**Comment by Mokto** [comment]
Yes, Meteor.user() is using Trackr but internally. You have to use it into getMeteorData.

react-komposer is the same as [new meteor 1.3 createContainer spec](http://guide.meteor.com/react.html#using-createContainer) right ? Because I will be adding this soon.

**Comment by smooJitter** [comment]
Actually, I believe createContainer is also built on top of meteor's getMeteorData.   @patrickml highlights a issues I brought up a few days ago. Discussion about how to handle data loading via react. My question for @patrickml, do you have trackr attached to your context configuration and what did you decide to use for local state.  A nice article about the approaches can be found here. 

https://www.discovermeteor.com/blog/data-loading-react/

**Comment by patrickml** [comment]
Il have to get back to you next when I get back from vacation. I cannot
remember exactly what I was doing.

**Comment by fermuch** [comment]
@patrickml any update? I'm curious to know how you did to handle mantra with RN meteor!

**Comment by patrickml** [comment]
Sorry I forgot about this ticket. Il write up details once I get the kids
to bed tonight.

**Comment by patrickml** [comment]
@smooJitter and @fermuch in order to use react-komposer I needed to import `trackr` which is an npm package modeled around Meteors `Tracker`

```
"react-komposer": "^1.8.0",
"trackr": "^2.0.2",
"trackr-reactive-var": "^1.4.0",
```

in order to use `react-komposer` i needed to make `trackr` global

i did this simply by adding this in my app.js file

```
import Trackr from 'trackr';

// react komposer needs tracker so we need to make it global
global.Tracker = Trackr;
```

After this, I had no problem using stateless components that are composed with react-komposer

```
const flex = ({ visibleHeight }) => (
  <View style={[styles.background, { height: visibleHeight }]}>
    <StatusBar barStyle="light-content" />
    <ProjectLists />
    <ActiveProject />
    <CreateTicket />
  </View>
);

flex.propTypes = {
  visibleHeight: PropTypes.number,
};

export default composeWithTracker((props, onData) => {
  onData(null, {});
}, Loading, Error)(flex);
```

@smooJitter as for the local state -- I've created a version of redux that runs on `Tracker` and is so so so much simpler -- I haven't finished the docs, but here is the repo https://github.com/patrickml/event-horizon

I have a local version of that package that is for react-native the only difference is I needed to import `"trackr-reactive-var": "^1.4.0"`

This allows me to do stuff like this

```
import EventHorizon from '../event-horizon/index';

const defaultConfig = {
  open: false,
  priority: 'normal',
  description: '',
  images: [],
};

EventHorizon.createStore('create-ticket', defaultConfig);

EventHorizon.createAction('create-ticket', 'OPEN_CREATE_TICKET_MODAL', (store, data, update) => {
  update({
    open: true,
  });
});

EventHorizon.createAction('create-ticket', 'CLOSE_CREATE_TICKET_MODAL', (store, data, update) => {
  update(defaultConfig);
});

EventHorizon.createAction('create-ticket', 'TICKET_UPDATE_PRIORITY', (store, priority, update) => {
  update({
    priority,
  });
});

EventHorizon.createAction('create-ticket', 'TICKET_ADD_IMAGE', (store, image, update) => {
  update({
    images: [
      ...store.images,
      image,
    ],
  });
});

EventHorizon.createAction('create-ticket', 'TICKET_REMOVE_IMAGE', (store, index, update) => {
  update({
    images: [
      ...store.images.slice(0, index),
      ...store.images.slice(index + 1),
    ],
  });
});
```

```
export default composeWithTracker((props, onData) => {
  onData(null, EventHorizon.subscribe('create-ticket'));
}, Loading, Loading)(TicketModal);
```

```
<Button
      text="submit"
      onPress={() => { EventHorizon.dispatch('CLOSE_CREATE_TICKET_MODAL'); }}
    />
```

I hope that helps!

**Comment by fermuch** [comment]
@patrickml thank you for answering so fast!

I was just writing back to you how I did the same but it wasn't working but for me, but I realized something:

`Meteor.status()` is not reactive. The docs says it is, but it doesn't for me.
For example:

```jsx
export const composer = ({context}, onData) => {
  const {Meteor} = context();
  onData(null, {status: Meteor.status().status});
};

export const depsMapper = (context) => ({
  context: () => context
});

export default composeAll(
  composeWithTracker(composer, Loading, Error),
  useDeps(depsMapper)
)(DebugConnection);
```


But then before posting my answer I tried to use `.subscribe` instead of `.status` and it works!
Tomorrow I'll try to debug a little more to know if the problem is on my side or in RN meteor.

**Comment by matb33** [comment]
None of the supposedly reactive methods exposed in react-native-meteor are actually reactive. `Meteor.status()` simply reads from `Data.ddp`, and `Meteor.collection().find()` etc reads from `minimongo-cache`, which is a fork of minimongo that isn't reactive. I find this a bit of a strange approach, as it forces you to use `createContainer` or `getMeteorData` -- i.e. you can't do: 
```
Tracker.autorun(() => {
  Meteor.status()
})
```
... and expect that to re-run each time `Meteor.status()` has changed. It will run once, and that's it. To be fair, the docs do state `These variables can be used inside getMeteorData or createContainer`. I expected that I could use them within a vanilla `Tracker.autorun`, but that's not the case.

What react-native-meteor is actually doing is that any DDP message it receives triggers a single `dep.changed()`, and all `createContainer`s etc are re-run as they `dep.depend()` on that single dependency. This means that any message coming via DDP will re-run _all_ `createContainer`s you have in your app.

This seems like a proof-of-concept type of approach, but I don't think should be the way to go moving forward. I'd suggest ditching `minimongo-cache` and instead using `minimongo` itself, and looking at what normal Meteor is doing when receiving DDP messages and how it handles granular invalidations.

**Comment by patrickml** [comment]
@matb33 thanks for the insight into this. I hadn't looked that far into this package yet. But this would explain the exact issues myself and others were experiencing

**Comment by Mokto** [comment]
Thanks for your feedback @matb33. I'll try to dig into this when I come back from my vacations in two weeks.

One question though, why would you use minimongo over minimongo-cache ?

@patrickml What issues are you talking about ?

**Comment by matb33** [comment]
Hey @Mokto, the reason I suggest minimongo (and specifically `LocalCollection`) is because it's built with reactivity throughout. By using minimongo-cache, you're effectively removing all the fine-grained reactivity that minimongo is capable of doing, and adding reactivity to the entire minimongo-cache -- any DDP message, even if it's unrelated to a collection, triggers this global invalidation and causes everything to re-run.

I'd also use `ReactiveVar` as well for `Meteor.status()` and pals. Upon receiving a DDP message for new data for it, you'd `.set` that ReactiveVar. Only the `createContainer`s or `autorun`s that use that ReactiveVar would re-run (as opposed to every single `createContainer` in the app).

The same thing applies to `createContainer`s or `autorun`s that use a particular collection. In fact, only the `.find()` queries that would be affected when changes are made would re-run. This is something that the Meteor devs strived really hard to achieve, i.e. prevent re-running queries where they could determine that re-running would make no difference.

When you receive DDP messages, you would either update the appropriate ReactiveVar (for Meteor.status etc) or the appropriate LocalCollection (for collections). You wouldn't have to manage any `Tracker.Dependency`s whatsoever, and `createContainer` and `getMeteorData` would simply be layers on top of `Tracker.autorun`.

**Comment by patrickml** [comment]
any updates for this?
