### ISSUE TITLE
Several instances

### ISSUE THREAD

**Issue by patrick-riemer** [inProgress-team/react-native-meteor#59]
I have the strange problem that if I use a navigation controller and have several components in the stack and use react-native-metor on more than one of them, that the second one does not work anymore.

For example:

In item 1 I display a MeteorListView, then I push a new component into the Navigator stack and do a Meteor.call in this component. The callback of Meteor.call is never called.

Is there any known problem with including several instances of Meteor?

**Comment by bubuzzz** [comment]
you connect to meteor server in the first component and let the 2nd one as if it is connected, is it ?

**Comment by patrick-riemer** [comment]
Yes, I think so.

I do not call the connect method in the second component. Do I have to connect in each single screen?

**Comment by bubuzzz** [comment]
i do :) i put `Meteor.connect` in every componentWillMount if i need that component connect to `meteor` it

**Comment by patrick-riemer** [comment]
Will this not increase the amount of sessions on the server each time?

I have integrated Kadira and get 4 sessions at the same time this method (as 4 components are open in the Navigator stack). As Meteor is using DDP, one connection should be able to handle that.

How do you handle this problem? Create a singleton wrapper around the Meteor or does react-native-meteor already come with anything like this included?

**Comment by smooJitter** [comment]
Try calling  'connect()' in root file where the controllers are defined.  

I had the the same problem however I am using react-native-navigation,the abstract layer of navigation controller.   According to react-native-meteor's documentation, 

   `Connect to a DDP server. You only have to do this once in your app.`

The issue may have something to do with 'react-native-controllers' approach with multiple root components.  ExNavigation relies on one root controller where the exnavigator stack is rendered inside a parent react-native component. Consider this call at the root of the example project,
   `
    @connectMeteor
    export default class RNApp extends Component {
          componentWillMount() {
              connect();
          }
    ...
    `
 This doesn't seem to work in the case of react-native-controllers. Notice the connection is made when the root component mounts. With RN controllers, we don't make the initial connection just before mounting a parent react root component because there is no parent root.  Since there are multiple roots, I tried calling Meteor.connect  inside  componentWillMount( ) for each root.  I assume you may be following a simular logic.  Oddly enough, calling connect() under componentWillMount( ) did not work but it did work after I called connect() via a button click.  In some instances, there seems to be an issue with evoking the connection just before the component mounts.  I refactored the example app to accomedate the approach taken by RN-controller, to get react-native-meteor to work, I simply called connect(), right after importing,

   `
import React, { Component, StyleSheet } from 'react-native';
import Meteor, { connectMeteor } from 'react-native-meteor';
import connect from './connect';
connect( );
   `
This worked for now.

**Comment by Mokto** [comment]
Hi,

Thank you for your feedbacks @smooJitter and @patrick-riemer.
Indeed, Meteor.connect has to be called only once. If needed you can call Meteor.reconnect().

You may use it in componentWillMount or right after importing Meteor (in your index.ios.js for example). It should works.

But it is true sometimes Meteor.call seem not to be triggered, I have to investigate this ! So I'll let this issue open.

**Comment by Mokto** [comment]
I confirm this bug also exists with react-native-router-flux.

I'm investigating this right now.

**Comment by Mokto** [comment]
Getting this issue if a subcomponent if of type='replace' and when switching between components.

But I really don't understand why ^^'.

Has anyone any idea ?

Thanks !

**Comment by Mokto** [comment]
Sorry guys for spamming. But it was unrelated. Just for your information, do NOT use DeviceEventEmitter.removeAllListeners :P

**Comment by Mokto** [comment]
Closing this since this is a react-native-controllers issue.

But yes, please connect ONLY ONCE in your app.

**Comment by smooJitter** [comment]
Mokto, can you explain your remarks regarding the DeviceEventEmitter

**Comment by Mokto** [comment]
When you call DeviceEventEmitter.removeAllListeners() it breaks the ddp connection.
