### ISSUE TITLE
Super expression must either be null or ....

### ISSUE THREAD

**Issue by atheriault** [inProgress-team/react-native-meteor#75]
I am trying to get your example up and running.  I created a new react-native app.  I went in and added the following import into the index.ios.js and I get the following error:

import Meteor, { createContainer } from 'react-native-meteor';

I get this error as soon as I have added the line.  I have used your command to install it and am running it on ios simulator.
npm i --save react-native-meteor@latest

As well I have went through and did the other installation instruction you require.  Same problem still occurs.  As soon as I add this import statement then the app doesn't work.  I remove it and re-run and it does.  Any idea what I am missing here?

![screen shot 2016-05-23 at 8 37 21 pm](https://cloud.githubusercontent.com/assets/7085109/15491547/6619ea0c-2126-11e6-9dbc-bbc43058f037.png)

**Comment by gopidon** [comment]
As per latest React Native version, u need to import React , Component from react modle and not react-native module.

It should be 
import React, {
  Component,
} from 'react';

rather than

import React, {
  Component,
  PropTypes,
  ListView
} from 'react-native';

as seen in most of the react-native-meteor source code such as ListView , Meteor etc. This is causing the error IMO.

**Comment by atheriault** [comment]
This I am doing as it is the default setup when creating a new react-native
project.

Any other possible solutions?

**Comment by gopidon** [comment]
Think u could go back to older react-native versions for the time being . It works for me in version 0.23.1

**Comment by Mokto** [comment]
Can you please share your code please ?

**Comment by gopidon** [comment]
Hi

I am using the latest react native code 0.26 and react-native-meteor version 1.0.0-rc. The straightforward examples as mentioned here do not work. I strongly believe the reason is as mentioned above. The module should be importing React from react and not react-native. Let me know if u need anything. Thanks

**Comment by hyperh** [comment]
+1 Same error after upgrading to 
```
    "react": "15.0.2",
    "react-native": "^0.26.2",
```

**Comment by valentinvichnal** [comment]
+1

**Comment by atheriault** [comment]
Downgrading to react 14.7 and react-native 22 did the trick. But obviously
a bug when using current react-native.

**Comment by Mokto** [comment]
Thanks for you help. It is now fixed in rc4 ;)
