### ISSUE TITLE
Example Code - "Edit Item" function does not seem to be updating MongoDB 

### ISSUE THREAD

**Issue by Wil-Ho** [inProgress-team/react-native-meteor#94]
Hi there,

Apologies if this is a stupid question as I am new.

However I have been playing with the example code and the "Edit Item" function does not seem to update the the list of item displayed on "Meteor List View".

I looked at my MongoDB on my server and the collections do not change after I press "Save". It seems to be me at least that the collection.update does not work?

Again apologies if there is something really obvious that I am missing, but any help would be greatly appreciated.

Cheers,

Wil

**Comment by fermuch** [comment]
Currently, updates are not reactive. You'll receive the update once it is updated on the server and comes back to the client. If it isn't updating on your server either, it might be a problem with permissions.

Think of react-native-meteor as a client, and updates can only be executed in the client if there are `allow`/`deny` rules on the server.



Also, it's a little easier to use `methods` instead of allow/deny rules, since they're easier to setup and maintain.

**Comment by Wil-Ho** [comment]
Thanks for the response.

I am just using the example code on the project. It can add items to the server via the meteor.call, it just seems to have promblems with the collection.update not going to the server. 

As you suggested I will look at any permission settings on my system that would prevent a collection.update.

Cheers

**Comment by Wil-Ho** [comment]
Thanks for the response.

I am just using the example code on the project. It can add items to the server via the meteor.call, it just seems to have problems with the collection.update not going to the server. 

As you suggested I will look at any permission settings on my system that would prevent a collection.update.

Cheers

**Comment by Mokto** [comment]
Hi @Wil-Ho,

Is it ok now ?
