### ISSUE TITLE
Vacations

### ISSUE THREAD

**Issue by Mokto** [inProgress-team/react-native-meteor#95]
Hi guys,

Sorry for not responding your issues, but i'm in vacations till july 7th.

Helping you soon.

**Comment by Mokto** [comment]
Sorry everyone for issues I have no time to deal with this right now, I should be able to help all of you mid august.

**Comment by funkyeah** [comment]
Hey @Mokto, a lot of the issues are questions about usage. I for one would prefer you to spend whatever time you have working on the actual project. May we can start a chatroom, forum, and or FAQ to bring some of the question based issues down.

**Comment by Mokto** [comment]
Hey !
Great idea ;)

What tool do you suggest ?

**Comment by funkyeah** [comment]
I'm mostly just brainstorming above because its fairly better to keep development moving ahead rather than getting bogged down in responding to issues that aren't bug related:

- for chat maybe gittr / slack, or a rocketchat instance if we want to stick with meteor
- for forum I suppose discourse is the goto, but would have to pay for the hosting
- FAQ could be just be part of the documentation if the same questions keep coming up

as far as which option would be the best, not really sure. Heck maybe just having someone help re-direct issues to stackoverflow and/or react-native resources if they are not specific to bugs in react-native-meteor would help keep the noise to a minimum.
